language: scala
scala:
  - 2.11.7
  - 2.10.6

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts clean coverage test

after_success:
  - codecov

before_install:
  - wget -O influxdb.deb https://s3.amazonaws.com/influxdb/influxdb_0.9.6.1_amd64.deb
  - sudo dpkg -i influxdb.deb
  - sudo cp src/test/resources/influxdb.conf /etc/influxdb/influxdb.conf
  - sudo service influxdb start
  - sleep 5; /usr/bin/influx --execute "CREATE USER influx_user WITH PASSWORD 'influx_password' WITH ALL PRIVILEGES"
  - pip install --user codecov
