language: scala
scala:
  - 2.11.7
  - 2.10.6

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts clean coverage test

after_success:
  - codecov

before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_0.9.4.1_amd64.deb
  - sudo dpkg -i influxdb_0.9.4.1_amd64.deb
  - sudo /etc/init.d/influxdb start
  - /opt/influxdb/influx --execute "CREATE USER influx_user WITH PASSWORD 'influx_password' WITH ALL PRIVILEGES"
  - sudo sed -i 's/auth-enabled = false/auth-enabled = true/' /etc/opt/influxdb/influxdb.conf
  - pip install --user codecov
