language: scala
scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts clean coverage test

after_success:
  - codecov

before_install:
  - wget --secure-protocol=TLSv1 -O influxdb.deb http://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i influxdb.deb
  - sudo cp src/test/resources/influxdb.conf /etc/influxdb/influxdb.conf
  - sudo service influxdb start
  - sleep 5; /usr/bin/influx --execute "CREATE USER influx_user WITH PASSWORD 'influx_password' WITH ALL PRIVILEGES"
  - pip install --user codecov
