language: scala
scala:
  - 2.11.7

script:
  - sbt -jvm-opts .travis.jvmopts clean coverage test

after_success:
  - codecov

before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_0.9.4.1_amd64.deb
  - sudo dpkg -i influxdb_0.9.4.1_amd64.deb
  - sudo /etc/init.d/influxdb start
  - pip install --user codecov
