language: scala
scala:
  - 2.12.0
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - curl -o influxdb.deb https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i influxdb.deb
  - sudo cp src/test/resources/influxdb.conf /etc/influxdb/influxdb.conf
  - sudo service influxdb start
  - sleep 5; /usr/bin/influx --execute "CREATE USER influx_user WITH PASSWORD 'influx_password' WITH ALL PRIVILEGES"
